[package]
name = "vjoy-linux"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.95", features = ["backtrace"] }
clap = { version = "4.5.28", features = ["derive"] }
evdev = "0.13.0"
ron = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
